# Generated by Django 5.1.4 on 2025-02-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='job_skills', to='hub.skills'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='user_qualifications', to='hub.qualifications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='user_skills', to='hub.skills'),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='job_qualifications', to='hub.qualifications'),
        ),
    ]
