# Generated by Django 5.1.4 on 2025-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_job_skills_userprofile_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
