# Generated by Django 5.1.4 on 2025-02-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(blank=True, choices=[('internal', 'internal'), ('external', 'external')], max_length=100, null=True),
        ),
    ]
