# Generated by Django 5.1.4 on 2025-02-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
    ]
