# Generated by Django 5.1.4 on 2025-02-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_remove_job_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vaccency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
