# Generated by Django 5.1.4 on 2025-02-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_application_address_application_age_application_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], default='Pending', max_length=20, null=True),
        ),
    ]
