# Generated by Django 5.1.4 on 2025-03-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_alter_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Hired', 'Hired'), ('Interview Scheduled', 'Interview Scheduled')], default='Pending', max_length=20, null=True),
        ),
    ]
