# Generated by Django 5.1.4 on 2025-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_application_interview_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='interview_location',
        ),
        migrations.RemoveField(
            model_name='application',
            name='interview_notes',
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
